fix: missing device_kernel_headers dependency
error: hardware/xiaomi/fingerprint/Android.bp:22:1: dependency "device_kernel_headers" of "libudfps_extension.xiaomi" missing