fix: missing device_kernel_headers for libjni_poweroffalarm
error: hardware/mediatek/PowerOffAlarm/Android.bp:26:1: dependency "device_kernel_headers" of "libjni_poweroffalarm" missing variant: